import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ApiError, Empty, ErrorState, formatDate, Loading, MetricCard, Notice, PageHeader, Panel, Pagination, ListResultSummary, Status, useData } from '@platform/shared';
import { ADMIN_PERMISSION_LABELS, WEBSITE_CONTENT_LABELS, downloadCsv, isoDateInput } from '../shared.jsx';

export function FileUploadPanel({ api, onDone }) {
  const [file, setFile] = useState(null); const [progress, setProgress] = useState(0); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); if (!file) return setMessage('请选择文件'); setBusy(true); setProgress(10); setMessage(''); try { await api.upload('admin/file-assets/upload', file, { category: 'MEDIA_ASSET', visibility: 'PUBLIC_PLATFORM' }, { onProgress: setProgress }); setMessage('文件上传成功'); setFile(null); onDone?.(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <Panel title="安全上传"><form onSubmit={submit} className="form-grid"><label>选择图片、音频、视频或 PDF<input type="file" onChange={(event) => setFile(event.target.files?.[0] || null)} disabled={busy} /></label><div className="row-actions"><button className="primary-button" disabled={busy || !file}>{busy ? `上传中 ${progress}%` : '上传文件'}</button>{message ? <span className="muted">{message}</span> : null}</div></form></Panel>;
}

export function AdminMaterials({ api }) {
  const [filters, setFilters] = useState({ search: '', status: '', category: '', visibility: '' });
  const [page, setPage] = useState(1); const [limit, setLimit] = useState(20); const [sort, setSort] = useState('created');
  const query = useMemo(() => { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); params.set('page', String(page)); params.set('limit', String(limit)); params.set('sort', sort); return params; }, [filters, page, limit, sort]);
  const materials = useData(() => api.get(`admin/materials?${query.toString()}`), [api, query]); const organizations = useData(() => api.get('admin/organizations/options'), [api]);
  const [form, setForm] = useState({ title: '', description: '', category: 'GENERAL', visibility: 'ALL_ORGS', orgIds: [], mimeType: '', resourceUrl: '', coverUrl: '' });
  const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [stats, setStats] = useState({ loading: false, data: null, error: null });
  async function create(event) {
    event.preventDefault(); setSaving(true); setMessage('');
    try { await api.post('admin/materials', { ...form, orgIds: form.visibility === 'ALL_ORGS' ? [] : form.orgIds }); setForm({ title: '', description: '', category: 'GENERAL', visibility: 'ALL_ORGS', orgIds: [], mimeType: '', resourceUrl: '', coverUrl: '' }); setMessage('物料元数据已保存。'); materials.refresh(); } catch (err) { setMessage(err.message); } finally { setSaving(false); }
  }
  async function toggle(item) { try { await api.put(`admin/materials/${item.id}`, { status: item.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }); materials.refresh(); } catch (err) { setMessage(err.message); } }
  async function loadStats(item) { setStats({ loading: true, data: null, error: null }); try { setStats({ loading: false, data: await api.get(`admin/materials/${item.id}/stats`), error: null }); } catch (error) { setStats({ loading: false, data: null, error }); } }
  return <>
    <PageHeader eyebrow="平台内容" title="素材与宣传物料" description="维护招生海报、课程介绍和活动资料的元数据、授权范围与真实使用统计。" actions={<button className="secondary-button" onClick={materials.refresh}>刷新</button>} />
    <Notice tone="info">上传文件与登记宣传物料分别管理；请为物料填写真实资源地址并设置授权范围。未配置资源的物料会显示“资源待配置”。</Notice>
    <FileUploadPanel api={api} onDone={materials.refresh} />
    <div className="split"><Panel title="新增宣传物料"><form onSubmit={create}>
      <label>名称<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label>说明<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>
      <div className="form-grid"><label>分类<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="GENERAL">通用</option><option value="COURSE">课程</option><option value="POSTER">海报</option><option value="ACTIVITY">活动</option><option value="PARTNERSHIP">合作</option></select></label><label>可见范围<select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value, orgIds: [] })}><option value="ALL_ORGS">全部机构</option><option value="ASSIGNED_ORGS">指定机构</option></select></label></div>
      {form.visibility === 'ASSIGNED_ORGS' ? <label>指定机构<select multiple value={form.orgIds} onChange={(e) => setForm({ ...form, orgIds: [...e.target.selectedOptions].map((option) => option.value) })}>{organizations.data?.items?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}
      <div className="form-grid"><label>MIME 类型（可选）<input value={form.mimeType} placeholder="application/pdf" onChange={(e) => setForm({ ...form, mimeType: e.target.value })} /></label><label>真实资源地址（可选）<input value={form.resourceUrl} placeholder="由外部存储决策后填写" onChange={(e) => setForm({ ...form, resourceUrl: e.target.value })} /></label></div>
      <label>封面地址（可选）<input value={form.coverUrl} onChange={(e) => setForm({ ...form, coverUrl: e.target.value })} /></label>
      {message ? <Notice tone={message.includes('失败') || message.includes('不能为空') ? 'danger' : 'success'}>{message}</Notice> : null}<button className="primary-button" disabled={saving}>{saving ? '保存中…' : '保存物料'}</button>
    </form></Panel><Panel title="物料授权"><Notice tone="info">“全部机构”会对所有状态正常的机构开放；“指定机构”只会在服务端向授权机构返回。教师与机构管理员均可查看机构可见物料。</Notice>{stats.loading ? <Loading label="正在读取统计…" /> : stats.error ? <ErrorState error={stats.error} /> : stats.data ? <><h3>{stats.data.material.title}</h3><div className="metrics"><MetricCard label="事件总数" value={stats.data.summary.totalEvents} hint={`${stats.data.summary.organizationCount} 家机构`} /><MetricCard label="查看" value={stats.data.summary.viewCount} hint="VIEW" tone="teal" /><MetricCard label="使用" value={stats.data.summary.useCount} hint="USE" tone="orange" /><MetricCard label="下载" value={stats.data.summary.downloadCount} hint="DOWNLOAD" tone="pink" /></div>{stats.data.organizations.length ? <div className="table-wrap"><table><thead><tr><th>机构</th><th>查看</th><th>使用</th><th>下载</th><th>最近事件</th></tr></thead><tbody>{stats.data.organizations.map((item) => <tr key={item.orgId}><td>{item.organizationName}</td><td>{item.viewCount}</td><td>{item.useCount}</td><td>{item.downloadCount}</td><td>{formatDate(item.lastEventAt)}</td></tr>)}</tbody></table></div> : <Empty title="暂无使用事件" />}</> : <Empty title="选择一条物料查看统计" />}</Panel></div>
    <Panel title="物料列表">{materials.loading || organizations.loading ? <Loading /> : materials.error ? <ErrorState error={materials.error} onRetry={materials.refresh} /> : materials.data?.items?.length ? <>
      <div className="filters"><input value={filters.search} placeholder="搜索物料名称或说明" onChange={(e) => { setFilters({ ...filters, search: e.target.value }); setPage(1); }} /><select value={filters.status} onChange={(e) => { setFilters({ ...filters, status: e.target.value }); setPage(1); }}><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select><select value={filters.category} onChange={(e) => { setFilters({ ...filters, category: e.target.value }); setPage(1); }}><option value="">全部分类</option><option value="GENERAL">通用</option><option value="COURSE">课程</option><option value="POSTER">海报</option><option value="ACTIVITY">活动</option><option value="PARTNERSHIP">合作</option></select><select value={filters.visibility} onChange={(e) => { setFilters({ ...filters, visibility: e.target.value }); setPage(1); }}><option value="">全部范围</option><option value="ALL_ORGS">全部机构</option><option value="ASSIGNED_ORGS">指定机构</option></select><select value={sort} onChange={(e) => { setSort(e.target.value); setPage(1); }}><option value="created">创建时间</option><option value="updated">更新时间</option><option value="title">标题</option><option value="events">使用次数</option></select><select value={limit} onChange={(e) => { setLimit(Number(e.target.value)); setPage(1); }}><option value="10">10 条/页</option><option value="20">20 条/页</option><option value="50">50 条/页</option></select></div>
      <ListResultSummary total={materials.data.total} page={materials.data.page} totalPages={materials.data.totalPages} label="个物料" /><div className="table-wrap"><table><thead><tr><th>物料</th><th>范围</th><th>资源</th><th>状态</th><th>使用次数</th><th>操作</th></tr></thead><tbody>{materials.data.items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><div className="muted">{item.category} · {item.description || '暂无说明'}</div></td><td>{item.visibility === 'ALL_ORGS' ? '全部机构' : `指定 ${item.assignedOrgCount}`}</td><td>{item.resourceConfigured ? <span className="status success">已配置</span> : <span className="muted">待配置</span>}</td><td><Status value={item.status} /></td><td>{item.eventCount}</td><td><div className="row-actions"><button className="secondary-button" onClick={() => loadStats(item)}>统计</button><button className="secondary-button" onClick={() => toggle(item)}>{item.status === 'ACTIVE' ? '停用' : '启用'}</button></div></td></tr>)}</tbody></table></div><Pagination page={materials.data.page} totalPages={materials.data.totalPages} onChange={setPage} disabled={materials.loading} /></> : <><div className="filters"><input value={filters.search} placeholder="搜索物料名称或说明" onChange={(e) => { setFilters({ ...filters, search: e.target.value }); setPage(1); }} /><select value={filters.status} onChange={(e) => { setFilters({ ...filters, status: e.target.value }); setPage(1); }}><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><Empty title="当前筛选条件下无物料" body="可以调整关键词、状态、分类或范围筛选条件。" /></>}</Panel>
  </>;
}

const CLIENT_PLATFORM_LABELS = { MACOS_APPLE: 'macOS（Apple 芯片）', WINDOWS_X64: 'Windows（64 位）' };
const CLIENT_CHANNEL_LABELS = { STABLE: '正式版', BETA: '测试版', INTERNAL: '内测版' };



