import { useState } from 'react';
import { NavLink } from 'react-router-dom';

export function AppShell({ product, roleLabel, user, navigation, onLogout, children }) {
  return <div className="app-shell"><aside className="sidebar"><div className="sidebar-top"><div className="brand"><span className="brand-mark">✦</span><span>{product}</span></div><div className="role-chip">{roleLabel}</div></div><nav className="app-nav">{navigation.map((item) => item.heading ? <p className="nav-heading" key={item.heading}>{item.heading}</p> : <NavLink key={item.to} to={item.to} className={({ isActive }) => 'nav-item' + (isActive ? ' active' : '')}><span className="nav-icon">{item.icon}</span>{item.label}{item.badge && <small>{item.badge}</small>}</NavLink>)}</nav><div className="sidebar-help"><span>✦</span><div><b>需要帮助？</b><small>查看开课与创作指南</small></div></div><div className="sidebar-footer"><div className="avatar">{(user?.displayName || user?.login || '?').slice(0, 1)}</div><div><strong>{user?.displayName || user?.login}</strong><small>{user?.login}</small></div><button className="icon-button" title="退出登录" onClick={onLogout}>↪</button></div></aside><main className="app-main"><div className="app-topbar"><span className="crumb">AI魔法学院 / {roleLabel}</span><div><span className="top-status">● 服务正常</span><button className="top-help">?</button></div></div><div className="page-content">{children}</div></main></div>;
}

export function LoginPanel({ title, description, clientType, demos = [], onLogin }) { const [login,setLogin]=useState(demos[0]?.login||'');const [password,setPassword]=useState(demos[0]?.password||'');const [pending,setPending]=useState(false);const [error,setError]=useState('');async function submit(e){e.preventDefault();setPending(true);setError('');try{await onLogin({login,password,clientType});}catch(err){setError(err.message||'登录失败');}finally{setPending(false)}}return <div className="login-page"><section className="login-intro"><div className="brand"><span className="brand-mark">✦</span><span>AI魔法学院</span></div><div className="login-orbit a"></div><div className="login-orbit b"></div><div className="login-copy"><p className="login-eyebrow">青少年 AI 创作开课平台</p><h1>{title}</h1><p>{description}</p><div className="login-points"><span>✦ 创作</span><span>✦ 课程</span><span>✦ 作品</span></div></div></section><section className="login-side"><div className="login-card"><p className="login-card-kicker">欢迎回来</p><h2>登录你的工作台</h2><p className="muted">使用机构或平台分配的账号进入。</p><form onSubmit={submit}><label>登录名<input value={login} onChange={e=>setLogin(e.target.value)} autoComplete="username" required/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<Notice tone="danger">{error}</Notice>}<button className="primary-button wide" disabled={pending}>{pending?'正在验证…':'进入工作台'} <span>↗</span></button></form>{demos.length>0&&<div className="demo-list"><span>演示账号</span>{demos.map(d=><button key={d.login} type="button" onClick={()=>{setLogin(d.login);setPassword(d.password)}}><strong>{d.label}</strong><small>{d.login}</small><b>使用</b></button>)}</div>}</div><small className="login-legal">AI魔法学院 · 为课堂创作而设计</small></section></div> }
export function PageHeader({ eyebrow, title, description, actions }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{actions&&<div className="header-actions">{actions}</div>}</header> }
export function MetricCard({ label, value, hint, tone='violet' }) { return <article className={'metric-card '+tone}><span className="metric-symbol">✦</span><p>{label}</p><strong>{value}</strong>{hint&&<small>{hint}</small>}</article> }
export function Notice({ tone='info', children }) { return <div className={'notice '+tone}>{children}</div> }
export function Loading({ label='正在加载数据…' }) { return <div className="loading"><span>✦</span>{label}</div> }
export function Empty({ title='暂时没有数据', body='数据出现后会显示在这里。' }) { return <div className="empty"><span>✦</span><strong>{title}</strong><p>{body}</p></div> }
export function ErrorState({ error,onRetry }) { return <Notice tone="danger">{error?.message||'加载失败'} {onRetry&&<button className="text-button" onClick={onRetry}>重试</button>}</Notice> }
export function Panel({ title, children, actions, className='' }) { return <section className={'panel '+className}><div className="panel-heading"><h2>{title}</h2>{actions}</div>{children}</section> }
export function Status({ value }) {const text=String(value||'UNKNOWN');const tone=/ACTIVE|PUBLISHED|APPROVED|SUCCESS|HOME_PRACTICE|ALWAYS_AVAILABLE/.test(text)?'success':/DRAFT|PENDING|TRIAL/.test(text)?'warning':'muted';return <span className={'status '+tone}>{text.replaceAll('_',' ')}</span> }