import { errors, rows } from '../lib.js';
const windows = new Map();
const active = new Map();
function positive(name, fallback, max = Number.MAX_SAFE_INTEGER) { const n = Number(process.env[name] || fallback); return Number.isFinite(n) && n > 0 ? Math.min(Math.floor(n), max) : fallback; }
function limits() { return { userPerHour: positive('FILE_UPLOAD_USER_PER_HOUR', 20, 10000), orgPerHour: positive('FILE_UPLOAD_ORG_PER_HOUR', 200, 100000), maxConcurrent: positive('FILE_UPLOAD_MAX_CONCURRENT', 3, 100), userBytes: positive('FILE_UPLOAD_USER_QUOTA_BYTES', 500 * 1024 * 1024, 100 * 1024 * 1024 * 1024), orgBytes: positive('FILE_UPLOAD_ORG_QUOTA_BYTES', 5 * 1024 * 1024 * 1024, 1024 * 1024 * 1024 * 1024) }; }
function key(scope, value) { return `${scope}:${value || 'anonymous'}`; }
function currentBytes(scope, value) { const clause = scope === 'org' ? 'owner_org_id=?' : 'owner_user_id=?'; return Number(rows(`SELECT COALESCE(SUM(file_size),0) AS bytes FROM file_assets WHERE ${clause} AND storage_kind='INTERNAL_PROXY' AND status != 'REMOVED'`, [value]).at(0)?.bytes || 0); }
function hit(keyValue, limit, now) { const start = now - 3600000; const prior = (windows.get(keyValue) || []).filter((time) => time > start); if (prior.length >= limit) return false; prior.push(now); windows.set(keyValue, prior); return true; }
export function reserveUpload({ userId, orgId, bytes }) { const cfg = limits(); const now = Date.now(); const userKey = key('user', userId); const orgKey = key('org', orgId); if ((active.get(userKey) || 0) >= cfg.maxConcurrent || (active.get(orgKey) || 0) >= cfg.maxConcurrent) throw errors.tooMany('上传并发数已达到上限，请稍后再试', 'UPLOAD_CONCURRENCY_LIMIT', { retryAfterSeconds: 10 }); if (!hit(`${userKey}:rate`, cfg.userPerHour, now)) throw errors.tooMany('个人上传频率已达到上限，请稍后再试', 'UPLOAD_USER_RATE_LIMIT', { windowSeconds: 3600 }); if (!hit(`${orgKey}:rate`, cfg.orgPerHour, now)) throw errors.tooMany('机构上传频率已达到上限，请稍后再试', 'UPLOAD_ORG_RATE_LIMIT', { windowSeconds: 3600 }); const size = Number(bytes || 0); const userBytes = currentBytes('user', userId); const orgBytes = currentBytes('org', orgId); if (userBytes + size > cfg.userBytes) throw errors.conflict('个人文件容量配额已用尽', 'UPLOAD_USER_QUOTA_EXCEEDED', { usedBytes: userBytes, quotaBytes: cfg.userBytes }); if (orgBytes + size > cfg.orgBytes) throw errors.conflict('机构文件容量配额已用尽', 'UPLOAD_ORG_QUOTA_EXCEEDED', { usedBytes: orgBytes, quotaBytes: cfg.orgBytes }); active.set(userKey, (active.get(userKey) || 0) + 1); active.set(orgKey, (active.get(orgKey) || 0) + 1); let released = false; return () => { if (released) return; released = true; for (const k of [userKey, orgKey]) { const n = (active.get(k) || 1) - 1; if (n > 0) active.set(k, n); else active.delete(k); } }; }
export function uploadLimitConfig() { return limits(); }
